version: '2'
services:
  ckan:
    container_name: ckan
    build: .
    depends_on:
      - db
      - solr
    links:
       - db
       - solr
    ports:
       - "80:80"
    environment:
      POSTGRES_USER: "ckan"
      POSTGRES_PASSWORD: "ckan"
      POSTGRES_DB: "ckan"
  db:
    container_name: db
    build: contrib/docker/postgresql
  solr:
    container_name: solr
    build: contrib/docker/solr
